### ISSUE TITLE
Gradle, Please

### ISSUE THREAD

**Issue by senorcris** [gotokatsuya/FlickableView#1]
Could you update so that:

compile 'com.github.goka.flickableview:flickableview:1.0.0'

Works from gradle?

**Comment by gotokatsuya** [comment]
@senorcris 

Thanks!

 I'm gonna release tomorrow.

**Comment by senorcris** [comment]
Awesome I can't wait to try it out.

**Comment by gotokatsuya** [comment]
@senorcris Released !
